### ISSUE TITLE
Subresource Integrity (SRI) not implemented, but all external resources are loaded over HTTPS

### ISSUE THREAD

**Issue by viperdriver100** [SharkyKZ/joomla-turnstile-plugin#2]
Can you please see if this is something that needs attention?
https://webbkoll.dataskydd.net/en
<img width="747" alt="Screenshot 2022-10-13 at 12 00 48" src="https://user-images.githubusercontent.com/9219295/195567666-30067d1f-0f94-4cb4-ba14-2e91ffaae0ea.png">

**Comment by bastiaanc** [comment]
Is it possible to simply copy the script and load it locally?
Or download it first so that it can load locally?

<img width="499" alt="Screenshot 2022-10-15 at 14 15 34" src="https://user-images.githubusercontent.com/9219295/195985944-087e9dfa-e097-49a8-8341-079317d3713a.png">

**Comment by SharkyKZ** [comment]
In short, no. From technical standpoint it might be possible. But the real issue is licensing. Cloudflare does not provide a downloadable script, the uncompressed version of the script or any licensing information. So it should be assumed that distributing their script is not allowed.

**Comment by bastiaanc** [comment]
Would you think this thing could be a problem with GDPR or Germany and their way of being extreme with sewing?

**Comment by SharkyKZ** [comment]
You best ask Cloudflare whether Turnstile is GDPR compliant. I'm not a legal expert. In case you are asking about local vs remote script, it makes no difference. The script loads an iframe from cloudflare.com so user data goes through there anyways. Answer is also verified remotely. Turnstile is a service, not software. It can not work locally.

**Comment by SharkyKZ** [comment]
I don't think there's anything to do here on my side. I'm closing this now.
