### ISSUE TITLE
Forms with Visforms

### ISSUE THREAD

**Issue by martinschaible** [SharkyKZ/joomla-turnstile-plugin#3]
Hello

We use Visforms for the forms of a website. After installation and configuration i tried to find the markup which you embedd in the form.
I couldn't see any markup related to Turnstile as described. Could it be, that Visform is not compatible? If yes, do you a recommendation for a form extension which works with your extension?

Many thanks!

**Comment by SharkyKZ** [comment]
Visforms has its own captcha implementation which does not support 3rd party captcha plugins by normal means. You'll have to ask form extension developers. From a quick look on JED, FlexiContact correctly uses Joomla's Captcha API.

**Comment by martinschaible** [comment]
Thanks! I go for FlexiContact.
