### ISSUE TITLE
Expired.

### ISSUE THREAD

**Issue by shane-clickingmad** [SharkyKZ/joomla-turnstile-plugin#4]
Turnstile errors with "Expired." if the page has been left open for some time prior to the user attempting to complete the human verification.

Looks like there is a client side API for this https://developers.cloudflare.com/turnstile/get-started/client-side-rendering/#access-a-widgets-state

**Comment by SharkyKZ** [comment]
Yes, it should refresh automatically after 8 seconds. The interval could be reduced by implementing `retry-interval` option. But note that it affects all failures, not just expiration.

**Comment by shane-clickingmad** [comment]
> If the page is left open for some time and the user completes the human verification by ticking the box, it may show as expired for me as well. However, without any intervention, it automatically refreshes (resets the Turnstile Captcha) after a few seconds and attempts to verify the user again. Is this not happening for you?

no this happens for us also, although we are having users complain they cant submit a form after seeing it. I guess 8 seconds is longer then the attention span of some.

**Comment by SharkyKZ** [comment]
Yes, callbacks and some other options are not exposed in the plugin. I'm OK with adding them. But will need to test first.

**Comment by SharkyKZ** [comment]
Callback options, as well as retry-interval, added in 1.4.0.
