### ISSUE TITLE
retrieve the current status using JavaScript even if implicit setup and server-side validation are used

### ISSUE THREAD

**Issue by bandizsolt** [SharkyKZ/joomla-turnstile-plugin#5]
Hi, I'd like to verify the status of this turnstile captcha with client-side JavaScript code. I understand that token verification happens server-side, and if it's successful, actions like submitting a contact form are allowed. However, I want to display a notification when the visitor clicks the submit button, indicating that if they need to perform an additional action for verification, they should do so. I've tried using this option: data-callback="javascriptCallback" but it doesn't seem to work. In summary, I want to display feedback when the visitor needs to click on the captcha when clicking the submit button, and if the captcha is successful/valid, I'll remove the feedback message. Using this callback JavaScript solution would be great to integrate my functionalities with the status changes.

![after submit pressed and ticket the box and writed some text](https://github.com/SharkyKZ/joomla-turnstile-plugin/assets/52448147/be6cc251-fa14-4691-be1a-ed97b8961687)
If the Turnstile Captcha cannot verify the user automatically or expires after some time, it requires manual intervention from the user:
![after submit pressed](https://github.com/SharkyKZ/joomla-turnstile-plugin/assets/52448147/fe9422bf-4cd1-4095-8141-977672a26c6d)

Can you please help with this?

**Comment by SharkyKZ** [comment]
I'm not sure there's a suitable callback for this. You probably need to listen for form submit event and from there check if Turnstile is checked. Based on documentation, you'd have to use `turnstile.getResponse()` in conjunction with `turnstile.isExpired()` to check for that.

**Comment by SharkyKZ** [comment]
Callback options added in 1.4.0.
