### ISSUE TITLE
Get $code value in triggerEvent() from request

### ISSUE THREAD

**Issue by Globulopolis** [SharkyKZ/joomla-turnstile-plugin#6]
Hi!
Code:
```php
try
{
	$app->triggerEvent('onCheckAnswer');
}
catch (Exception $e)
{
	...
}
```

will always return error. Because an empty `$code` value provided.

So we need to add value like this

`$app->triggerEvent('onCheckAnswer', array($app->input->getCmd('turnstile')));`

in component or just add a fallback, before https://github.com/SharkyKZ/joomla-turnstile-plugin/blob/master/code/plugins/captcha/turnstile/turnstile.php#L218

`$code = $code ?? $input->getCmd('turnstile');`

**Comment by SharkyKZ** [comment]
This is not a valid way to use Captcha. Captcha plugins were never meant to use plugin events. They must be triggered through `Joomla\CMS\Captcha\Captcha` class.
